USE northwind;
SELECT * FROM products;

-- 1) Write a query to list the product id, product name, and unit price of every product that Northwind sells. (Hint: To help set up your query, look at the schema preview to seewhat column names belong to each table. Or use SELECT * to query all columnsfirst, then refine your query to just the columns you want.)
-- List of producst sold by Northwind: productID: 1, productname: Chai, unit price: 18.00; productID: 2, productname: Chang, unit price: 19.00; productID: 3, productname: Aniseed Syrup, unit price: 10.00; productID: 4, product name: Chef Anton's Cajun Seasoning, unit price: 22.00; productID: 5, product name: Chef Anton's Gumbo Mix, unit price: 21.35; productID: 6, product name: Grandma's Boysenberry Spread, unit price: 25.00; productID: 7, product name: Uncle Bob's Organic Dried Pears, unit price: 30.00; productID: 8, product name: Northwoods Cranberry Sauce, unit price: 40.00; productID: 9, product name: Mishi Kobe Niku, unit price: 97.00; productID: 10, product name: Ikura, unit price: 31.00; productID: 11, product name: Queso Cabrales, unit price: 21.00; productID: 12, product name: Queso Manchego La Pastora, unit price: 38.00; productID: 13, product name: Konbu, unit price: 6.00; productID: 14, product name: Tofu, unit price: 23.25; productID: 15, product name: Genen Shouyu, unit price: 15.50; productID: 16, product name: Pavlova, unit price: 17.45;
-- productID: 17, product name: Alice Mutton, unit price: 39.00; productID: 18, product name: Carnarvon Tigers, unit price: 62.50; productID: 19, product name: Teatime Chocolate Biscuits, unit price: 9.20; productID: 20, product name: Sir Rodney's Marmalade, unit price: 81.00; productID: 21, product name: Sir Rodney's Scones, unit price: 10.00; productID: 22, product name: Gustaf's Knckebrd, unit price: 21.00; productID: 23, product name: Tunnbrd, unit price: 9.00; productID: 24, product name: Guaran Fantstica, unit price: 4.50; productID: 25, product name: NuNuCa Nu-Nougat-Creme, unit price: 14.00; productID: 26, product name: Gumbr Gummibrchen, unit price: 31.23; productID: 27, product name: Schoggi Schokolade, unit price: 43.90; productID: 28, product name: Rssle Sauerkraut, unit price: 45.60; productID: 29, product name: Thringer Rostbratwurst, unit price: 123.79; productID: 30, product name: Nord-Ost Matjeshering, unit price: 25.89; productID: 31, product name: Gorgonzola Telino, unit price: 12.50; productID: 32, product name: Mascarpone Fabioli, unit price: 32.00; productID: 33, product name: Geitost, unit price: 2.50;
-- productID: 34, product name: Sasquatch Ale, unit price: 14.00; productID: 35, product name: Steeleye Stout, unit price: 18.00; productID: 36, product name: Inlagd Sill, unit price: 19.00; productID: 37, product name: Gravad lax, unit price:26.00; productID: 38, product name: Cte de Blaye, unit price: 263.50; productID: 39, product name: Chartreuse verte, unit price: 18.00; productID: 40, product name: Boston Crab Meat, unit price: 18.40; productID: 41, product name: Jack's New England Clam Chowder, unit price: 9.65; productID: 42, product name: Singaporean Hokkien Fried Mee, unit price: 14.00; productID: 43, product name: Ipoh Coffee, unit price: 46.00; productID: 44, product name: Gula Malacca, unit price: 19.45; productID: 45, product name: Rogede sild, unit price: 9.50; productID: 46, product name: Spegeslid, unit price: 12.00; productID: 47, product name: Zaanse koeken, unit price: 9.50; productID: 48, product name: Chocolade, unit price: 12.75; 
-- productID: 49, product name: Maxilaku, unit price: 20.00; productID: 50, product name: Valkoinen suklaa, unit price: 16.25; productID: 51, product name: Manjump Dried Apples, unit price: 53.00; productID: 52, product name: Filo Mix, unti price: 7.00; productID: 53, product name: Perth Pastries, unit price: 32.80; productID: 54, product name: Tourtire, unit price: 7.45; productID: 55, product name: Pt chinois, unit price: 24.00; productID: 56, product name: Gnocchi di nonna Alice, unit price: 38.00; productID: 57, product name: Ravioli Angelo, unit price: 19.50; productID: 58, product name: Escargots de Bourgogne, unit price: 13.25; productID: 59, product name: Raclette Courdavault, unit price: 55.00; productID: 60, product name: Camembert Pierrot, unit price: 34.00; 
-- productID: 61, product name: Sirop d'rable, unit price: 28.50; productID: 62, product name: Tarte au sucre, unit price: 49.30; productID: 63, product name: Vegie-spread, unit price: 43.90; productID: 64, product name: Wimmers gute Semmelkndel, unit price: 33.25; productID: 65, product name: Louisiana Fiery Hot Pepper Sauce, unit price: 21.05; productID: 66, product name: Louisiana Hot Spiced Okra, unit price: 17.00; productID: 67, product name: Laughing Lumberjack Lager, unit price: 14.00; productID: 68, product name: Scottish Longbreads, unit price: 12.50; productID: 69, product name: Gudbrandsdalsost, unit price: 36.00; productID: 70, product name: Outback Lager, unit price: 15.00; productID: 71, product name: Flotemysost, unit price: 21.50; productID: 72, product name: Mozzarella di Giovanni, unit price: 34.80; productID: 73, product name: Rd Kaviar, unit price: 15.00: productID: 74, product name: Longlife Tofu, unit price: 10.00; productID: 75, product name: Rhnbru Klosterbier, unit price: 7.75; productID: 76, product name: Lakkalikri, unit price: 18.00; productID: 77, product name: Original Frankfurter grne Soe, unit price: 13.00.

-- 2) Write a query to identify the products where the unit price is $7.50 or less.
-- The products where the unit price is $7.50 or less are Geitost, Guaran Fantastica, Konbu, Filo Mix, and Tourtire. 

-- 3) What are the products that we carry where we have no units on hand, but 1 or more units are on backorder? Write a query that answers this question.
-- Products where we have no units on hand are Chef Anton's Gumbo Mix, Alice Mutton, Thringer Rostbratwurst, Gorgonzola Telino, and Perth Pasties; and the products where we have one or more units on back order are Ipoh Coffee, Gnocchi di nonna Alice, Scottish Longbreads, Outback Lager, Longlife Tofu, Queso Cabrales, Chang, Sir Rodney's Scones, Mascarpone Fabioli, Gravad lax, Maxilaku, Aniseed Syrup, Gorgonzola Telino, Rogede sild, Chocolade, Wimmers gute Semmelkndel, Louisiana Hot Spiced Okra. 

-- 4) Examine the products table. How does it identify the type (category) of each item sold? Where can you find a list of all categories? Write a set of queries to answer these questions, ending with a query that creates a list of all the seafood items we carry.
-- It identifies the type of each item sold by listing the product name and the type of quantities per unit that have been bought as well; you can find the list of all categories in the Categories table and it lists the name of the categories of the products that are being sold; and the seafood products that we do carry are Ikura, Konbu, Carnarvon Tigers, Nord-Ost Matjeshering, Inlagd Sill, Gravad lax, Boston Crab Meat, Jack's New England Claim Chowder, Rogede sild, Spegesild, Escargots de Bourgogne, and Rd Kaviar. 
SELECT * FROM categories;
SELECT * FROM products;

-- 5) Examine the products table again. How do you know what supplier each product comes from? Where can you find info on suppliers? Write a set of queries to find the specific identifier for "Tokyo Traders" and then find all products from that supplier.
-- In the products table, you can tell what supplier the products come from by looking at the supplier ID column. You can find the information on the suppliers in the suppliers table. The specific identifier for Tokyo Traders is supplierID 4 and the products that they sell are Mishi Kobe Niku, Ikura, and Longlife Tofu. 
SELECT * FROM suppliers;
SELECT * FROM products;

-- 6) How many employees work at northwind? What employees have "manager" somewhere in their job title? Write queries to answer each question.
-- Northwind has nine employees in total. The employees that have "manager" somewhere in their job title is Steven Buchanan. 
SELECT * FROM employees;