-- =====================================================
-- Sakila SQL Solutions for Business Analysis Questions
-- Each section contains the SQL solution and explanation
-- April 23,2026
-- =====================================================

-- =====================================================
-- Question 1:
-- Calculate the total revenue generated by each store,
-- including earliest and latest payment dates.
-- =====================================================

USE sakila;

SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue,
    MIN(p.payment_date) AS start_date,
    MAX(p.payment_date) AS end_date
FROM payment p
JOIN staff st ON p.staff_id = st.staff_id
JOIN store s ON st.store_id = s.store_id
GROUP BY s.store_id;

-- Explanation:
-- Payments are linked to staff, and staff are linked to stores.
-- SUM calculates total revenue, MIN and MAX define the reporting period.


-- =====================================================
-- Question 2:
-- Show monthly revenue breakdown for each store.
-- =====================================================
SELECT 
    s.store_id,
    DATE_FORMAT(p.payment_date, '%Y-%m') AS revenue_month,
    SUM(p.amount) AS monthly_revenue
FROM payment p
JOIN staff st ON p.staff_id = st.staff_id
JOIN store s ON st.store_id = s.store_id
GROUP BY s.store_id, DATE_FORMAT(p.payment_date, '%Y-%m')
ORDER BY s.store_id, revenue_month;

-- Explanation:
-- DATE_FORMAT groups revenue by month and year.
-- Revenue is aggregated monthly for each store.


-- =====================================================
-- Question 3:
-- Compare each store's revenue to total company revenue.
-- =====================================================
WITH store_revenue AS (
    SELECT 
        s.store_id,
        SUM(p.amount) AS revenue
    FROM payment p
    JOIN staff st ON p.staff_id = st.staff_id
    JOIN store s ON st.store_id = s.store_id
    GROUP BY s.store_id
),
company_total AS (
    SELECT SUM(revenue) AS total_revenue FROM store_revenue
)
SELECT 
    sr.store_id,
    sr.revenue,
    ct.total_revenue,
    ROUND((sr.revenue / ct.total_revenue) * 100, 2) AS revenue_percent
FROM store_revenue sr
CROSS JOIN company_total ct;

-- Explanation:
-- First calculate revenue by store, then total company revenue.
-- CROSS JOIN makes the company total available to each row.


-- =====================================================
-- Question 4:
-- Number of rentals per month and average payment by category.
-- =====================================================
SELECT 
    DATE_FORMAT(r.rental_date, '%Y-%m') AS rental_month,
    c.name AS category_name,
    COUNT(r.rental_id) AS rental_count,
    ROUND(AVG(p.amount), 2) AS avg_payment
FROM rental r
JOIN payment p ON r.rental_id = p.rental_id
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film_category fc ON i.film_id = fc.film_id
JOIN category c ON fc.category_id = c.category_id
GROUP BY rental_month, c.name
ORDER BY rental_month, rental_count DESC;

-- Explanation:
-- Rentals connect to inventory, then film categories.
-- COUNT gives transactions and AVG gives average payment per category.


-- =====================================================
-- Question 5:
-- Rank stores by revenue, rentals, and average customer payment.
-- =====================================================
SELECT 
    s.store_id,
    SUM(p.amount) AS total_revenue,
    COUNT(r.rental_id) AS total_rentals,
    ROUND(AVG(p.amount), 2) AS avg_payment,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS revenue_rank
FROM store s
JOIN staff st ON s.store_id = st.store_id
JOIN payment p ON st.staff_id = p.staff_id
JOIN rental r ON p.rental_id = r.rental_id
GROUP BY s.store_id;

-- Explanation:
-- Aggregate store metrics and rank them by total revenue.


-- =====================================================
-- Question 6:
-- Identify highest revenue-generating categories for each store.
-- =====================================================
SELECT *
FROM (
    SELECT 
        s.store_id,
        c.name AS category_name,
        SUM(p.amount) AS total_revenue,
        RANK() OVER (PARTITION BY s.store_id ORDER BY SUM(p.amount) DESC) AS revenue_rank
    FROM payment p
    JOIN rental r ON p.rental_id = r.rental_id
    JOIN inventory i ON r.inventory_id = i.inventory_id
    JOIN store s ON i.store_id = s.store_id
    JOIN film_category fc ON i.film_id = fc.film_id
    JOIN category c ON fc.category_id = c.category_id
    GROUP BY s.store_id, c.name
) ranked_categories
WHERE revenue_rank = 1;

-- Explanation:
-- Revenue is summed per category per store.
-- Window ranking identifies the top category for each store.


-- =====================================================
-- Question 7:
-- Rank customers within each store by spending and rentals.
-- =====================================================
SELECT 
    s.store_id,
    CONCAT(c.first_name, ' ', c.last_name) AS customer_name,
    SUM(p.amount) AS total_spent,
    COUNT(r.rental_id) AS rental_count,
    RANK() OVER (PARTITION BY s.store_id ORDER BY SUM(p.amount) DESC) AS customer_rank
FROM customer c
JOIN store s ON c.store_id = s.store_id
JOIN payment p ON c.customer_id = p.customer_id
JOIN rental r ON p.rental_id = r.rental_id
GROUP BY s.store_id, c.customer_id;

-- Explanation:
-- Customer totals are grouped within each store.
-- Ranking identifies top customers by spending.


-- =====================================================
-- Question 8:
-- Analyze monthly rental trends by category.
-- =====================================================
WITH monthly_category AS (
    SELECT 
        DATE_FORMAT(r.rental_date, '%Y-%m') AS rental_month,
        c.name AS category_name,
        COUNT(*) AS total_rentals
    FROM rental r
    JOIN inventory i ON r.inventory_id = i.inventory_id
    JOIN film_category fc ON i.film_id = fc.film_id
    JOIN category c ON fc.category_id = c.category_id
    GROUP BY rental_month, c.name
)
SELECT 
    rental_month,
    category_name,
    total_rentals,
    total_rentals - LAG(total_rentals) OVER (
        PARTITION BY category_name ORDER BY rental_month
    ) AS month_over_month_change
FROM monthly_category;

-- Explanation:
-- LAG compares current month rentals to previous month rentals.


-- =====================================================
-- Question 9:
-- Measure staff performance.
-- =====================================================
SELECT 
    st.staff_id,
    CONCAT(st.first_name, ' ', st.last_name) AS staff_name,
    COUNT(r.rental_id) AS rentals_processed,
    SUM(p.amount) AS total_revenue,
    ROUND(SUM(p.amount)/COUNT(r.rental_id), 2) AS avg_revenue_per_rental,
    RANK() OVER (ORDER BY SUM(p.amount) DESC) AS revenue_rank
FROM staff st
JOIN payment p ON st.staff_id = p.staff_id
JOIN rental r ON p.rental_id = r.rental_id
GROUP BY st.staff_id;

-- Explanation:
-- Staff are ranked by revenue generated and average revenue per rental.


-- =====================================================
-- Question 10:
-- Identify categories with declining monthly revenue.
-- =====================================================
WITH monthly_revenue AS (
    SELECT 
        DATE_FORMAT(p.payment_date, '%Y-%m') AS revenue_month,
        c.name AS category_name,
        SUM(p.amount) AS revenue
    FROM payment p
    JOIN rental r ON p.rental_id = r.rental_id
    JOIN inventory i ON r.inventory_id = i.inventory_id
    JOIN film_category fc ON i.film_id = fc.film_id
    JOIN category c ON fc.category_id = c.category_id
    GROUP BY revenue_month, c.name
)
SELECT 
    revenue_month,
    category_name,
    revenue,
    LAG(revenue) OVER (PARTITION BY category_name ORDER BY revenue_month) AS prev_month_revenue,
    revenue - LAG(revenue) OVER (PARTITION BY category_name ORDER BY revenue_month) AS revenue_difference
FROM monthly_revenue
ORDER BY revenue_difference ASC;

-- Explanation:
-- Categories with the largest negative revenue difference are declining.
-- These are candidates for management focus next quarter.
