USE sakila;

-- Question 1: Determine the total rental revenue generated by each store, including the earliest and latest payment dates. 
-- Objectives: Calculating total rental revenue for each store and the earliest and latest payment dates
-- Store ID's to work with: store_id = 1 and store_id = 2. 

-- Total Rental Revenue for store_id = 1: 
SELECT MIN(payment_date) AS 'Earliest Payment Date',
        MAX(payment_date) AS 'Latest Payment Date',
        SUM(amount) AS 'Total Revenue for store_1'
FROM payment
WHERE staff_id = (SELECT staff_id FROM staff WHERE store_id = 1);
-- Total Revenue for store_id 1 is $33482.50, the earliest payment date is 05/24/2005, and the latest payment date is 02/14/2006. 

-- Total Revenue for store_id = 2: 
SELECT MIN(payment_date) AS 'Earliest Payment Date',
		MAX(payment_date) AS 'Latest Payment Date',
		SUM(amount) AS 'Total Revenue for store_2'
FROM payment 
WHERE staff_id = (SELECT staff_id FROM staff WHERE store_id = 2);
-- Total Revenue for store_id 2 is $33924.06, the earliest payment date is 05/24/2005 and the latest payment date is 02/14/2006. 

-- 2.) Analyze the month-by-month revenue breakdown for each store. 
SELECT 
    s.store_id AS 'Store',
    MONTH(p.payment_date) AS 'Month',
    YEAR(p.payment_date) AS 'Year',
    SUM(p.amount) AS 'Monthly Revenue'
FROM payment p
JOIN staff st ON p.staff_id = st.staff_id
JOIN store s ON st.store_id = s.store_id
GROUP BY s.store_id, YEAR(p.payment_date), MONTH(p.payment_date)
ORDER BY s.store_id, Year, Month;
-- Month-by-Month Revenue for Store 1: May of 2006 = 2621.83, June of 2005 4774.37, July of 2005 = 13998.56, August of 2005 = 11853.65, and February of 2006 = 234.09

-- Month-by-Month Revenue for Store 2: May of 2005 = 2201.61, June of 2005 = 4855.52, July of 2005 = 14370.35, August of 2005 = 12216.49, and February of 2006 = 280.69.

-- 3.) Compare total rental revenue between stores and calculate percentage contribution. 
WITH total_revenue AS (
    SELECT SUM(amount) AS grand_total
    FROM payment)
SELECT 
    s.store_id AS 'Store',
    SUM(p.amount) AS 'Total Revenue',
    ROUND((SUM(p.amount) / t.grand_total) * 100, 2) AS 'Percentage of Total Revenue'
FROM payment p
JOIN staff st ON p.staff_id = st.staff_id
JOIN store s ON st.store_id = s.store_id
CROSS JOIN total_revenue t
GROUP BY s.store_id, t.grand_total
ORDER BY s.store_id;
-- Store 1's Percentage of Total Revenue = 49.67
-- Store 2's Percentage of Total Revenue = 50.33

-- 4.) Evaluate rentals per month and average payment per category. 
